Family Name: StrangerSans 

Fonts:

  Regular:
    MONO: 0
    CASL: 0.7
    wght: 450
    slnt: 0
    CRSV: 0

  Italic:
    MONO: 1
    CASL: 0.7
    wght: 450
    slnt: -10
    CRSV: 0

  Bold:
    MONO: 0
    CASL: 0.7
    wght: 750
    slnt: 0
    CRSV: 0

  Bold Italic:
    MONO: 0
    CASL: 0.7
    wght: 750
    slnt: -10
    CRSV: 0

Code Ligatures: False

Features:
- ss01 # Single-story a
- ss02 # Single-story g
- ss03 # Simplified f
- ss04 # Simplified i
- ss05 # Simplified l
# - ss06 # Simplified r
- ss07 # Simplified italic diagonals (kwxyz)
- ss08 # Serifless L and Z
- ss09 # Simplified 6 and 9
- ss10 # Dotted 0
- ss11 # Simplified 1
- ss12 # Simplified @
